// <auto-generated />
using System;
using AverageTemperatureApplication.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AverageTemperatureApplication.Migrations
{
    [DbContext(typeof(AverageTemperatureContext))]
    [Migration("20221015223923_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AverageTemperatureApplication.Database.CachedTemperatures", b =>
                {
                    b.Property<int>("CachedTemperaturesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CachedTemperaturesId"), 1L, 1);

                    b.Property<DateTime>("Day")
                        .HasColumnType("datetime2");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<double>("Temperature")
                        .HasColumnType("float");

                    b.HasKey("CachedTemperaturesId");

                    b.ToTable("CachedTemperatures");
                });

            modelBuilder.Entity("AverageTemperatureApplication.Database.UserApiKeys", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("UserCount")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("UserApiKeys");
                });
#pragma warning restore 612, 618
        }
    }
}
